#Campos

'''

ID
STATUS_ID: -> TABLA STATUS / CAMPOS: SYM 
FECHA_CREACION
FECHA_MODIFICACION
FECHA_CIERRE
CREADO_POR_ID_ -> TABLA CONTACTO / CAMPOS: LAST_NAME, FIRST_NAME
MODIFICADO_POR_ID: -> TABLA CONTACTO / CAMPOS:LAST_NAME, FIRST_NAME
ASIGNADO_ID: -> TABLA CONTACTO / CAMPOS :LAST_NAME, FIRST_NAME EJ:(TELECOM)
ORGANIZACION_ID: -> TABLA ORGANIZACION EJ: DISU/COTA/ O HC, PDVSA, GUARDIANES DEL ALBA
GRUPO_ID: -> TABLA CONTACTO / LAST_NAME, FIRST_NAME EJ: TELECOM_RADIOCOMUNICACIONES
AFECTADO_ID -> TABLA CONTACTO / LAST_NAME, FIRST_NAME
SOLICITANTE_ID: -> TABLA CONTACTO / LAST_NAME, FIRST_NAME
CATEGORIA_ID O PROBLEMA_ID -> TABLA CATEGORIA / CAMPOS SYM EJ: Rad.Trunking.Falla, Rad.Buscapersonas.Req
PRIORIDAD_ID -> TABLA PRIORIDAD
SUMARY O ASUNTO
DETALLE
'''

'''
ID:1
STATUS_ID: 1 (ABIERTO)
FECHA_CREACION: 27/02/2013
FECHA_MODIFICACION: 27/02/2013
FECHA_CIERRE:VACIO
CREADO_POR_ID:125 CARLOS GARCIA
MODIFICADO_POR_ID: 125 CARLOS GARCIA
ASIGNADO_ID: 5135 (SISTEMAS)
ORGANIZACION_ID: 2156 (HOSPITAL COROMOTO)
GRUPO_ID: 1553 (SISTEMAS_DESARROLLO_PROPIO)
AFECTADO_ID:165 (DAYANA PEÑA)
SOLICITANTE_ID: 5956 (LUIS LINARES)
CATEGORIA_ID: 21698 (Sistemas.Propios.Admision.Falla)
PRIORIDAD_ID: 2 (ALTA)
SUMMARY O ASUNTO: (Reporta controles duplicados)
DETALLE: (La Usuario reporta falla al moment de imprimir un control, le aparece ducpliado)


'''
