# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/contactos.ui'
#
# Created: Mon Mar 18 15:44:31 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_Form(QtGui.QWidget):
    def __init__(self):
        super(Ui_Form, self).__init__()
        #elf.setObjectName("Form")
        #self.resize(1085, 492)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNuevo = QtGui.QPushButton()
        self.btnNuevo.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/30px-Crystal_Clear_app_List_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon)
        self.btnNuevo.setObjectName("btnNuevo")
        self.horizontalLayout.addWidget(self.btnNuevo)
        self.btnModificar = QtGui.QPushButton()
        self.btnModificar.setEnabled(False)
        self.btnModificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/40px-Crystal_Clear_app_kedit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon1)
        self.btnModificar.setObjectName("btnModificar")
        self.horizontalLayout.addWidget(self.btnModificar)
        self.btnEliminar = QtGui.QPushButton()
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/30px_1 (514).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon2)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.btnDeshacer = QtGui.QPushButton()
        self.btnDeshacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/40px_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeshacer.setIcon(icon3)
        self.btnDeshacer.setObjectName("btnDeshacer")
        self.horizontalLayout.addWidget(self.btnDeshacer)
        self.btnLimpiar = QtGui.QPushButton()
        self.btnLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon4)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.horizontalLayout.addWidget(self.btnLimpiar)
        self.btnExportar = QtGui.QPushButton()
        self.btnExportar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/OfficeExcel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportar.setIcon(icon5)
        self.btnExportar.setObjectName("btnExportar")
        self.horizontalLayout.addWidget(self.btnExportar)
        spacerItem = QtGui.QSpacerItem(380, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSalir = QtGui.QPushButton()
        self.btnSalir.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/25px_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon6)
        self.btnSalir.setObjectName("btnSalir")
        self.horizontalLayout.addWidget(self.btnSalir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.lblId = QtGui.QLabel()
        self.lblId.setObjectName("lblId")
        self.gridLayout.addWidget(self.lblId, 1, 0)
        self.txtId = QtGui.QLineEdit()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtId.sizePolicy().hasHeightForWidth())
        self.txtId.setSizePolicy(sizePolicy)
        self.txtId.setObjectName("txtId")
        self.gridLayout.addWidget(self.txtId, 1, 1)
        self.tableWidget = QtGui.QTableWidget()
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 3, 14, 1)
        self.lblCedula = QtGui.QLabel()
        self.lblCedula.setObjectName("lblCedula")
        self.gridLayout.addWidget(self.lblCedula, 2, 0)
        self.txtCedula = QtGui.QLineEdit()
        self.txtCedula.setObjectName("txtCedula")
        self.gridLayout.addWidget(self.txtCedula, 2, 1)
        self.lblCodigp = QtGui.QLabel()
        self.lblCodigp.setObjectName("lblCodigp")
        self.gridLayout.addWidget(self.lblCodigp, 3, 0)
        self.txtCodigp = QtGui.QLineEdit()
        self.txtCodigp.setObjectName("txtCodigp")
        self.gridLayout.addWidget(self.txtCodigp, 3, 1)
        self.lblNombre = QtGui.QLabel()
        self.lblNombre.setObjectName("lblNombre")
        self.gridLayout.addWidget(self.lblNombre, 4, 0)
        self.txtNombre = QtGui.QLineEdit()
        self.txtNombre.setObjectName("txtNombre")
        self.gridLayout.addWidget(self.txtNombre, 4, 1)
        self.lblApellido = QtGui.QLabel()
        self.lblApellido.setObjectName("lblApellido")
        self.gridLayout.addWidget(self.lblApellido, 5, 0)
        self.txtApellido = QtGui.QLineEdit()
        self.txtApellido.setObjectName("txtApellido")
        self.gridLayout.addWidget(self.txtApellido, 5, 1)
        self.lblUsuarioRed = QtGui.QLabel()
        self.lblUsuarioRed.setObjectName("lblUsuarioRed")
        self.gridLayout.addWidget(self.lblUsuarioRed, 6, 0)
        self.txtUsuarioRed = QtGui.QLineEdit()
        self.txtUsuarioRed.setObjectName("txtUsuarioRed")
        self.gridLayout.addWidget(self.txtUsuarioRed, 6, 1)
        self.lblTipoContacto = QtGui.QLabel()
        self.lblTipoContacto.setObjectName("lblTipoContacto")
        self.gridLayout.addWidget(self.lblTipoContacto, 7, 0)
        self.cbxTipoContacto = QtGui.QComboBox()
        self.cbxTipoContacto.setObjectName("cbxTipoContacto")
        self.gridLayout.addWidget(self.cbxTipoContacto, 7, 1)
        self.lblTelfOficina = QtGui.QLabel()
        self.lblTelfOficina.setObjectName("lblTelfOficina")
        self.gridLayout.addWidget(self.lblTelfOficina, 8, 0)
        self.txtTelefonoOficina = QtGui.QLineEdit()
        self.txtTelefonoOficina.setObjectName("txtTelefonoOficina")
        self.gridLayout.addWidget(self.txtTelefonoOficina, 8, 1)
        self.lblMovil = QtGui.QLabel()
        self.lblMovil.setObjectName("lblMovil")
        self.gridLayout.addWidget(self.lblMovil, 9, 0)
        self.txtTelefonoMovil = QtGui.QLineEdit()
        self.txtTelefonoMovil.setObjectName("txtTelefonoMovil")
        self.gridLayout.addWidget(self.txtTelefonoMovil, 9, 1)
        self.lblEmail = QtGui.QLabel()
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 10, 0)
        self.txtEmail = QtGui.QLineEdit()
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout.addWidget(self.txtEmail, 10, 1)
        self.lblDpto = QtGui.QLabel()
        self.lblDpto.setObjectName("lblDpto")
        self.gridLayout.addWidget(self.lblDpto, 11, 0)
        self.txtDpto = QtGui.QLineEdit()
        self.txtDpto.setObjectName("txtDpto")
        self.gridLayout.addWidget(self.txtDpto, 11, 1)
        self.btnBuscarDpto = QtGui.QPushButton()
        self.btnBuscarDpto.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/contactos/apartment-2-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarDpto.setIcon(icon7)
        self.btnBuscarDpto.setObjectName("btnBuscarDpto")
        self.gridLayout.addWidget(self.btnBuscarDpto, 11, 2)
        self.lblLocalidad = QtGui.QLabel()
        self.lblLocalidad.setObjectName("lblLocalidad")
        self.gridLayout.addWidget(self.lblLocalidad, 12, 0)
        self.txtLocalidad = QtGui.QLineEdit()
        self.txtLocalidad.setObjectName("txtLocalidad")
        self.gridLayout.addWidget(self.txtLocalidad, 12, 1)
        self.btnBuscarLocalidad = QtGui.QPushButton()
        self.btnBuscarLocalidad.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/contactos/map-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarLocalidad.setIcon(icon8)
        self.btnBuscarLocalidad.setObjectName("btnBuscarLocalidad")
        self.gridLayout.addWidget(self.btnBuscarLocalidad, 12, 2)
        self.lblUbicacion = QtGui.QLabel()
        self.lblUbicacion.setObjectName("lblUbicacion")
        self.gridLayout.addWidget(self.lblUbicacion, 13, 0)
        self.txtUbicacion = QtGui.QLineEdit()
        self.txtUbicacion.setObjectName("txtUbicacion")
        self.gridLayout.addWidget(self.txtUbicacion, 13, 1)
        self.btnBuscarUbicacion = QtGui.QPushButton()
        self.btnBuscarUbicacion.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/contactos/building-5-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarUbicacion.setIcon(icon9)
        self.btnBuscarUbicacion.setObjectName("btnBuscarUbicacion")
        self.gridLayout.addWidget(self.btnBuscarUbicacion, 13, 2)
        self.lblObservacion = QtGui.QLabel()
        self.lblObservacion.setObjectName("lblObservacion")
        self.gridLayout.addWidget(self.lblObservacion, 14, 0)
        self.txtObservacion = QtGui.QLineEdit()
        self.txtObservacion.setObjectName("txtObservacion")
        self.gridLayout.addWidget(self.txtObservacion, 14, 1)
        self.setGeometry(300, 300, 250, 150)
        self.setLayout(self.gridLayout)
        #self.retranslateUi()
        #QtCore.QMetaObject.connectSlotsByName()
    '''
    def retranslateUi(self):
        self.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNuevo.setText(QtGui.QApplication.translate("Form", "  &Nuevo  ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificar.setText(QtGui.QApplication.translate("Form", "&Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminar.setText(QtGui.QApplication.translate("Form", "&Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeshacer.setText(QtGui.QApplication.translate("Form", "&Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLimpiar.setText(QtGui.QApplication.translate("Form", "&Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setToolTip(QtGui.QApplication.translate("Form", "Exportar consulta a MS Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setText(QtGui.QApplication.translate("Form", "&Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setText(QtGui.QApplication.translate("Form", "    &Salir   ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblId.setText(QtGui.QApplication.translate("Form", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("Form", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodigp.setText(QtGui.QApplication.translate("Form", "Codigo", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("Form", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.lblApellido.setText(QtGui.QApplication.translate("Form", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsuarioRed.setText(QtGui.QApplication.translate("Form", "Usuario de Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipoContacto.setText(QtGui.QApplication.translate("Form", "Tipo Contacto", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelfOficina.setText(QtGui.QApplication.translate("Form", "Telef. Oficina", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMovil.setText(QtGui.QApplication.translate("Form", "Telef. Movil", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("Form", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDpto.setText(QtGui.QApplication.translate("Form", "Departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocalidad.setText(QtGui.QApplication.translate("Form", "Localidad", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUbicacion.setText(QtGui.QApplication.translate("Form", "Ubicacion", None, QtGui.QApplication.UnicodeUTF8))
        self.lblObservacion.setText(QtGui.QApplication.translate("Form", "Observacion", None, QtGui.QApplication.UnicodeUTF8))
    '''


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mySW = Ui_Form()
    mySW.show()
    sys.exit(app.exec_())
