# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/contactos.ui'
#
# Created: Wed Mar 27 22:39:37 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 616)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNuevo = QtGui.QPushButton(Form)
        self.btnNuevo.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/30px-Crystal_Clear_app_List_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon)
        self.btnNuevo.setObjectName("btnNuevo")
        self.horizontalLayout.addWidget(self.btnNuevo)
        self.btnModificar = QtGui.QPushButton(Form)
        self.btnModificar.setEnabled(False)
        self.btnModificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/40px-Crystal_Clear_app_kedit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon1)
        self.btnModificar.setObjectName("btnModificar")
        self.horizontalLayout.addWidget(self.btnModificar)
        self.btnEliminar = QtGui.QPushButton(Form)
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/30px_1 (514).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon2)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.btnDeshacer = QtGui.QPushButton(Form)
        self.btnDeshacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/40px_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeshacer.setIcon(icon3)
        self.btnDeshacer.setObjectName("btnDeshacer")
        self.horizontalLayout.addWidget(self.btnDeshacer)
        self.btnLimpiar = QtGui.QPushButton(Form)
        self.btnLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon4)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.horizontalLayout.addWidget(self.btnLimpiar)
        self.btnExportar = QtGui.QPushButton(Form)
        self.btnExportar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buscar20px"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportar.setIcon(icon5)
        self.btnExportar.setObjectName("btnExportar")
        self.horizontalLayout.addWidget(self.btnExportar)
        spacerItem = QtGui.QSpacerItem(380, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSalir = QtGui.QPushButton(Form)
        self.btnSalir.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../img/25px_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon6)
        self.btnSalir.setObjectName("btnSalir")
        self.horizontalLayout.addWidget(self.btnSalir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 2, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.lblId = QtGui.QLabel(Form)
        self.lblId.setObjectName("lblId")
        self.gridLayout.addWidget(self.lblId, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem2 = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 3, 14, 1)
        self.lblCedula = QtGui.QLabel(Form)
        self.lblCedula.setObjectName("lblCedula")
        self.gridLayout.addWidget(self.lblCedula, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        self.lblCodigp = QtGui.QLabel(Form)
        self.lblCodigp.setObjectName("lblCodigp")
        self.gridLayout.addWidget(self.lblCodigp, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.lblNombre = QtGui.QLabel(Form)
        self.lblNombre.setObjectName("lblNombre")
        self.gridLayout.addWidget(self.lblNombre, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 1, 1, 1)
        self.lblApellido = QtGui.QLabel(Form)
        self.lblApellido.setObjectName("lblApellido")
        self.gridLayout.addWidget(self.lblApellido, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 1, 1, 1)
        self.lblUsuarioRed = QtGui.QLabel(Form)
        self.lblUsuarioRed.setObjectName("lblUsuarioRed")
        self.gridLayout.addWidget(self.lblUsuarioRed, 8, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 1, 1, 1)
        self.lblTipoContacto = QtGui.QLabel(Form)
        self.lblTipoContacto.setObjectName("lblTipoContacto")
        self.gridLayout.addWidget(self.lblTipoContacto, 9, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_8.addWidget(self.comboBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_8, 9, 1, 1, 1)
        self.lblTelfOficina = QtGui.QLabel(Form)
        self.lblTelfOficina.setObjectName("lblTelfOficina")
        self.gridLayout.addWidget(self.lblTelfOficina, 10, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_9.addWidget(self.lineEdit_8)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_9, 10, 1, 1, 1)
        self.lblMovil = QtGui.QLabel(Form)
        self.lblMovil.setObjectName("lblMovil")
        self.gridLayout.addWidget(self.lblMovil, 11, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_10.addWidget(self.lineEdit_9)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_10, 11, 1, 1, 1)
        self.lblEmail = QtGui.QLabel(Form)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 12, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_11.addWidget(self.lineEdit_10)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_11, 12, 1, 1, 1)
        self.lblDpto = QtGui.QLabel(Form)
        self.lblDpto.setObjectName("lblDpto")
        self.gridLayout.addWidget(self.lblDpto, 13, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_12.addWidget(self.lineEdit_11)
        self.btnBuscarDpto = QtGui.QPushButton(Form)
        self.btnBuscarDpto.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../img/contactos/apartment-2-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarDpto.setIcon(icon7)
        self.btnBuscarDpto.setObjectName("btnBuscarDpto")
        self.horizontalLayout_12.addWidget(self.btnBuscarDpto)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_12, 13, 1, 1, 1)
        self.lblLocalidad = QtGui.QLabel(Form)
        self.lblLocalidad.setObjectName("lblLocalidad")
        self.gridLayout.addWidget(self.lblLocalidad, 14, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_13.addWidget(self.lineEdit_12)
        self.btnBuscarLocalidad = QtGui.QPushButton(Form)
        self.btnBuscarLocalidad.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../img/contactos/map-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarLocalidad.setIcon(icon8)
        self.btnBuscarLocalidad.setObjectName("btnBuscarLocalidad")
        self.horizontalLayout_13.addWidget(self.btnBuscarLocalidad)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_13, 14, 1, 1, 1)
        self.lblUbicacion = QtGui.QLabel(Form)
        self.lblUbicacion.setObjectName("lblUbicacion")
        self.gridLayout.addWidget(self.lblUbicacion, 15, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_14.addWidget(self.lineEdit_13)
        self.btnBuscarUbicacion = QtGui.QPushButton(Form)
        self.btnBuscarUbicacion.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../img/contactos/building-5-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarUbicacion.setIcon(icon9)
        self.btnBuscarUbicacion.setObjectName("btnBuscarUbicacion")
        self.horizontalLayout_14.addWidget(self.btnBuscarUbicacion)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout_14, 15, 1, 1, 1)
        self.lblObservacion = QtGui.QLabel(Form)
        self.lblObservacion.setObjectName("lblObservacion")
        self.gridLayout.addWidget(self.lblObservacion, 16, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_15.addWidget(self.lineEdit_14)
        self.gridLayout.addLayout(self.horizontalLayout_15, 16, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNuevo.setText(QtGui.QApplication.translate("Form", "  &Nuevo  ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificar.setText(QtGui.QApplication.translate("Form", "&Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminar.setText(QtGui.QApplication.translate("Form", "&Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeshacer.setText(QtGui.QApplication.translate("Form", "&Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLimpiar.setText(QtGui.QApplication.translate("Form", "&Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setToolTip(QtGui.QApplication.translate("Form", "Exportar consulta a MS Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setText(QtGui.QApplication.translate("Form", "&Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setText(QtGui.QApplication.translate("Form", "    &Salir   ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblId.setText(QtGui.QApplication.translate("Form", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("Form", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodigp.setText(QtGui.QApplication.translate("Form", "Codigo", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("Form", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.lblApellido.setText(QtGui.QApplication.translate("Form", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsuarioRed.setText(QtGui.QApplication.translate("Form", "Usuario de Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipoContacto.setText(QtGui.QApplication.translate("Form", "Tipo Contacto", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelfOficina.setText(QtGui.QApplication.translate("Form", "Telef. Oficina", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMovil.setText(QtGui.QApplication.translate("Form", "Telef. Movil", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("Form", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDpto.setText(QtGui.QApplication.translate("Form", "Departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocalidad.setText(QtGui.QApplication.translate("Form", "Localidad", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUbicacion.setText(QtGui.QApplication.translate("Form", "Ubicacion", None, QtGui.QApplication.UnicodeUTF8))
        self.lblObservacion.setText(QtGui.QApplication.translate("Form", "Observacion", None, QtGui.QApplication.UnicodeUTF8))

import recursos_rc
