# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/contactos.ui'
#
# Created: Tue Mar 19 10:51:22 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1032, 616)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnNuevo = QtGui.QPushButton(Form)
        self.btnNuevo.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../img/30px-Crystal_Clear_app_List_manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon)
        self.btnNuevo.setObjectName(_fromUtf8("btnNuevo"))
        self.horizontalLayout.addWidget(self.btnNuevo)
        self.btnModificar = QtGui.QPushButton(Form)
        self.btnModificar.setEnabled(False)
        self.btnModificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../img/40px-Crystal_Clear_app_kedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon1)
        self.btnModificar.setObjectName(_fromUtf8("btnModificar"))
        self.horizontalLayout.addWidget(self.btnModificar)
        self.btnEliminar = QtGui.QPushButton(Form)
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../img/30px_1 (514).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon2)
        self.btnEliminar.setObjectName(_fromUtf8("btnEliminar"))
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.btnDeshacer = QtGui.QPushButton(Form)
        self.btnDeshacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../img/40px_reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeshacer.setIcon(icon3)
        self.btnDeshacer.setObjectName(_fromUtf8("btnDeshacer"))
        self.horizontalLayout.addWidget(self.btnDeshacer)
        self.btnLimpiar = QtGui.QPushButton(Form)
        self.btnLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../img/erase.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon4)
        self.btnLimpiar.setObjectName(_fromUtf8("btnLimpiar"))
        self.horizontalLayout.addWidget(self.btnLimpiar)
        self.btnExportar = QtGui.QPushButton(Form)
        self.btnExportar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../img/OfficeExcel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportar.setIcon(icon5)
        self.btnExportar.setObjectName(_fromUtf8("btnExportar"))
        self.horizontalLayout.addWidget(self.btnExportar)
        spacerItem = QtGui.QSpacerItem(380, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSalir = QtGui.QPushButton(Form)
        self.btnSalir.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../img/25px_exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon6)
        self.btnSalir.setObjectName(_fromUtf8("btnSalir"))
        self.horizontalLayout.addWidget(self.btnSalir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.lblId = QtGui.QLabel(Form)
        self.lblId.setObjectName(_fromUtf8("lblId"))
        self.gridLayout.addWidget(self.lblId, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem1 = QtGui.QSpacerItem(400, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 2, 3, 14, 1)
        self.lblCedula = QtGui.QLabel(Form)
        self.lblCedula.setObjectName(_fromUtf8("lblCedula"))
        self.gridLayout.addWidget(self.lblCedula, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.lblCodigp = QtGui.QLabel(Form)
        self.lblCodigp.setObjectName(_fromUtf8("lblCodigp"))
        self.gridLayout.addWidget(self.lblCodigp, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.lblNombre = QtGui.QLabel(Form)
        self.lblNombre.setObjectName(_fromUtf8("lblNombre"))
        self.gridLayout.addWidget(self.lblNombre, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.lblApellido = QtGui.QLabel(Form)
        self.lblApellido.setObjectName(_fromUtf8("lblApellido"))
        self.gridLayout.addWidget(self.lblApellido, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 1, 1, 1)
        self.lblUsuarioRed = QtGui.QLabel(Form)
        self.lblUsuarioRed.setObjectName(_fromUtf8("lblUsuarioRed"))
        self.gridLayout.addWidget(self.lblUsuarioRed, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 1, 1, 1)
        self.lblTipoContacto = QtGui.QLabel(Form)
        self.lblTipoContacto.setObjectName(_fromUtf8("lblTipoContacto"))
        self.gridLayout.addWidget(self.lblTipoContacto, 8, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_8.addWidget(self.comboBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_8, 8, 1, 1, 1)
        self.lblTelfOficina = QtGui.QLabel(Form)
        self.lblTelfOficina.setObjectName(_fromUtf8("lblTelfOficina"))
        self.gridLayout.addWidget(self.lblTelfOficina, 9, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_9.addWidget(self.lineEdit_8)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_9, 9, 1, 1, 1)
        self.lblMovil = QtGui.QLabel(Form)
        self.lblMovil.setObjectName(_fromUtf8("lblMovil"))
        self.gridLayout.addWidget(self.lblMovil, 10, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_10.addWidget(self.lineEdit_9)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_10, 10, 1, 1, 1)
        self.lblEmail = QtGui.QLabel(Form)
        self.lblEmail.setObjectName(_fromUtf8("lblEmail"))
        self.gridLayout.addWidget(self.lblEmail, 11, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_11.addWidget(self.lineEdit_10)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_11, 11, 1, 1, 1)
        self.lblDpto = QtGui.QLabel(Form)
        self.lblDpto.setObjectName(_fromUtf8("lblDpto"))
        self.gridLayout.addWidget(self.lblDpto, 12, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_12.addWidget(self.lineEdit_11)
        self.btnBuscarDpto = QtGui.QPushButton(Form)
        self.btnBuscarDpto.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../img/contactos/apartment-2-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarDpto.setIcon(icon7)
        self.btnBuscarDpto.setObjectName(_fromUtf8("btnBuscarDpto"))
        self.horizontalLayout_12.addWidget(self.btnBuscarDpto)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_12, 12, 1, 1, 1)
        self.lblLocalidad = QtGui.QLabel(Form)
        self.lblLocalidad.setObjectName(_fromUtf8("lblLocalidad"))
        self.gridLayout.addWidget(self.lblLocalidad, 13, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_13.addWidget(self.lineEdit_12)
        self.btnBuscarLocalidad = QtGui.QPushButton(Form)
        self.btnBuscarLocalidad.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../img/contactos/map-4-24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarLocalidad.setIcon(icon8)
        self.btnBuscarLocalidad.setObjectName(_fromUtf8("btnBuscarLocalidad"))
        self.horizontalLayout_13.addWidget(self.btnBuscarLocalidad)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_13, 13, 1, 1, 1)
        self.lblUbicacion = QtGui.QLabel(Form)
        self.lblUbicacion.setObjectName(_fromUtf8("lblUbicacion"))
        self.gridLayout.addWidget(self.lblUbicacion, 14, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.horizontalLayout_14.addWidget(self.lineEdit_13)
        self.btnBuscarUbicacion = QtGui.QPushButton(Form)
        self.btnBuscarUbicacion.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../img/contactos/building-5-24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarUbicacion.setIcon(icon9)
        self.btnBuscarUbicacion.setObjectName(_fromUtf8("btnBuscarUbicacion"))
        self.horizontalLayout_14.addWidget(self.btnBuscarUbicacion)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_14, 14, 1, 1, 1)
        self.lblObservacion = QtGui.QLabel(Form)
        self.lblObservacion.setObjectName(_fromUtf8("lblObservacion"))
        self.gridLayout.addWidget(self.lblObservacion, 15, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.horizontalLayout_15.addWidget(self.lineEdit_14)
        self.gridLayout.addLayout(self.horizontalLayout_15, 15, 1, 1, 1)
        self.setLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNuevo.setText(QtGui.QApplication.translate("Form", "  &Nuevo  ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificar.setText(QtGui.QApplication.translate("Form", "&Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminar.setText(QtGui.QApplication.translate("Form", "&Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeshacer.setText(QtGui.QApplication.translate("Form", "&Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLimpiar.setText(QtGui.QApplication.translate("Form", "&Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setToolTip(QtGui.QApplication.translate("Form", "Exportar consulta a MS Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setText(QtGui.QApplication.translate("Form", "&Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setText(QtGui.QApplication.translate("Form", "    &Salir   ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblId.setText(QtGui.QApplication.translate("Form", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("Form", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodigp.setText(QtGui.QApplication.translate("Form", "Codigo", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("Form", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.lblApellido.setText(QtGui.QApplication.translate("Form", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsuarioRed.setText(QtGui.QApplication.translate("Form", "Usuario de Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipoContacto.setText(QtGui.QApplication.translate("Form", "Tipo Contacto", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelfOficina.setText(QtGui.QApplication.translate("Form", "Telef. Oficina", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMovil.setText(QtGui.QApplication.translate("Form", "Telef. Movil", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("Form", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDpto.setText(QtGui.QApplication.translate("Form", "Departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocalidad.setText(QtGui.QApplication.translate("Form", "Localidad", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUbicacion.setText(QtGui.QApplication.translate("Form", "Ubicacion", None, QtGui.QApplication.UnicodeUTF8))
        self.lblObservacion.setText(QtGui.QApplication.translate("Form", "Observacion", None, QtGui.QApplication.UnicodeUTF8))

