# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/contactos.ui'
#
# Created: Fri Mar 15 13:48:36 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 725)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 222, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 222, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        Form.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/contactos/user-6-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1101, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 242, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 153, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 242, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 242, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 153, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 242, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 242, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 153, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 115, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 230, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.btnNuevo = QtGui.QPushButton(self.widget)
        self.btnNuevo.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.btnNuevo.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/30px-Crystal_Clear_app_List_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon1)
        self.btnNuevo.setObjectName("btnNuevo")
        self.btnModificar = QtGui.QPushButton(self.widget)
        self.btnModificar.setEnabled(False)
        self.btnModificar.setGeometry(QtCore.QRect(110, 10, 91, 41))
        self.btnModificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/40px-Crystal_Clear_app_kedit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon2)
        self.btnModificar.setObjectName("btnModificar")
        self.btnEliminar = QtGui.QPushButton(self.widget)
        self.btnEliminar.setGeometry(QtCore.QRect(210, 10, 91, 41))
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/30px_1 (514).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon3)
        self.btnEliminar.setObjectName("btnEliminar")
        self.btnDeshacer = QtGui.QPushButton(self.widget)
        self.btnDeshacer.setGeometry(QtCore.QRect(310, 10, 91, 41))
        self.btnDeshacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/40px_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeshacer.setIcon(icon4)
        self.btnDeshacer.setObjectName("btnDeshacer")
        self.btnSalir = QtGui.QPushButton(self.widget)
        self.btnSalir.setGeometry(QtCore.QRect(1000, 10, 91, 41))
        self.btnSalir.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../img/25px_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon5)
        self.btnSalir.setObjectName("btnSalir")
        self.btnLimpiar = QtGui.QPushButton(self.widget)
        self.btnLimpiar.setGeometry(QtCore.QRect(410, 10, 91, 41))
        self.btnLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../img/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon6)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.txtId = QtGui.QLineEdit(Form)
        self.txtId.setGeometry(QtCore.QRect(10, 100, 61, 23))
        self.txtId.setObjectName("txtId")
        self.lblId = QtGui.QLabel(Form)
        self.lblId.setGeometry(QtCore.QRect(10, 80, 62, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblId.setPalette(palette)
        self.lblId.setObjectName("lblId")
        self.lblCedula = QtGui.QLabel(Form)
        self.lblCedula.setGeometry(QtCore.QRect(80, 80, 62, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblCedula.setPalette(palette)
        self.lblCedula.setObjectName("lblCedula")
        self.txtCedula = QtGui.QLineEdit(Form)
        self.txtCedula.setGeometry(QtCore.QRect(80, 100, 101, 23))
        self.txtCedula.setObjectName("txtCedula")
        self.txtCodigo = QtGui.QLineEdit(Form)
        self.txtCodigo.setGeometry(QtCore.QRect(190, 100, 101, 23))
        self.txtCodigo.setObjectName("txtCodigo")
        self.lblCodigo = QtGui.QLabel(Form)
        self.lblCodigo.setGeometry(QtCore.QRect(190, 80, 62, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblCodigo.setPalette(palette)
        self.lblCodigo.setObjectName("lblCodigo")
        self.lblNombre = QtGui.QLabel(Form)
        self.lblNombre.setGeometry(QtCore.QRect(300, 80, 62, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblNombre.setPalette(palette)
        self.lblNombre.setObjectName("lblNombre")
        self.txtNombre = QtGui.QLineEdit(Form)
        self.txtNombre.setGeometry(QtCore.QRect(300, 100, 231, 23))
        self.txtNombre.setObjectName("txtNombre")
        self.txtApellido = QtGui.QLineEdit(Form)
        self.txtApellido.setGeometry(QtCore.QRect(540, 100, 231, 23))
        self.txtApellido.setObjectName("txtApellido")
        self.lblApellido = QtGui.QLabel(Form)
        self.lblApellido.setGeometry(QtCore.QRect(540, 80, 62, 15))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblApellido.setPalette(palette)
        self.lblApellido.setObjectName("lblApellido")
        self.lblUsuarioRed = QtGui.QLabel(Form)
        self.lblUsuarioRed.setGeometry(QtCore.QRect(780, 80, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblUsuarioRed.setPalette(palette)
        self.lblUsuarioRed.setObjectName("lblUsuarioRed")
        self.txtUsuario_Red = QtGui.QLineEdit(Form)
        self.txtUsuario_Red.setGeometry(QtCore.QRect(780, 100, 121, 23))
        self.txtUsuario_Red.setObjectName("txtUsuario_Red")
        self.lblTipoContacto = QtGui.QLabel(Form)
        self.lblTipoContacto.setGeometry(QtCore.QRect(910, 80, 161, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTipoContacto.setPalette(palette)
        self.lblTipoContacto.setObjectName("lblTipoContacto")
        self.cbxTipoContacto = QtGui.QComboBox(Form)
        self.cbxTipoContacto.setGeometry(QtCore.QRect(910, 100, 171, 23))
        self.cbxTipoContacto.setEditable(False)
        self.cbxTipoContacto.setObjectName("cbxTipoContacto")
        self.lblTelefonoOficina = QtGui.QLabel(Form)
        self.lblTelefonoOficina.setGeometry(QtCore.QRect(10, 140, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTelefonoOficina.setPalette(palette)
        self.lblTelefonoOficina.setObjectName("lblTelefonoOficina")
        self.txtTelefono_Oficina = QtGui.QLineEdit(Form)
        self.txtTelefono_Oficina.setGeometry(QtCore.QRect(10, 160, 121, 23))
        self.txtTelefono_Oficina.setObjectName("txtTelefono_Oficina")
        self.lblTelefonoMovil = QtGui.QLabel(Form)
        self.lblTelefonoMovil.setGeometry(QtCore.QRect(140, 140, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTelefonoMovil.setPalette(palette)
        self.lblTelefonoMovil.setObjectName("lblTelefonoMovil")
        self.txtTelefono_Movil = QtGui.QLineEdit(Form)
        self.txtTelefono_Movil.setGeometry(QtCore.QRect(140, 160, 121, 23))
        self.txtTelefono_Movil.setObjectName("txtTelefono_Movil")
        self.txtEmail = QtGui.QLineEdit(Form)
        self.txtEmail.setGeometry(QtCore.QRect(270, 160, 191, 23))
        self.txtEmail.setObjectName("txtEmail")
        self.lblEmail = QtGui.QLabel(Form)
        self.lblEmail.setGeometry(QtCore.QRect(270, 140, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblEmail.setPalette(palette)
        self.lblEmail.setObjectName("lblEmail")
        self.btnBuscarDpto = QtGui.QPushButton(Form)
        self.btnBuscarDpto.setGeometry(QtCore.QRect(740, 160, 31, 23))
        self.btnBuscarDpto.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../img/contactos/apartment-2-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarDpto.setIcon(icon7)
        self.btnBuscarDpto.setObjectName("btnBuscarDpto")
        self.lblDpto = QtGui.QLabel(Form)
        self.lblDpto.setGeometry(QtCore.QRect(470, 140, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblDpto.setPalette(palette)
        self.lblDpto.setObjectName("lblDpto")
        self.txtIdDepartamento = QtGui.QLineEdit(Form)
        self.txtIdDepartamento.setGeometry(QtCore.QRect(470, 160, 41, 23))
        self.txtIdDepartamento.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtIdDepartamento.setObjectName("txtIdDepartamento")
        self.txtDepartamento = QtGui.QLineEdit(Form)
        self.txtDepartamento.setGeometry(QtCore.QRect(510, 160, 231, 23))
        self.txtDepartamento.setObjectName("txtDepartamento")
        self.btnBuscarLocalidad = QtGui.QPushButton(Form)
        self.btnBuscarLocalidad.setGeometry(QtCore.QRect(1050, 160, 31, 23))
        self.btnBuscarLocalidad.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../img/contactos/map-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarLocalidad.setIcon(icon8)
        self.btnBuscarLocalidad.setObjectName("btnBuscarLocalidad")
        self.lblLocalidad = QtGui.QLabel(Form)
        self.lblLocalidad.setGeometry(QtCore.QRect(780, 140, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblLocalidad.setPalette(palette)
        self.lblLocalidad.setObjectName("lblLocalidad")
        self.txtIdLocalidad = QtGui.QLineEdit(Form)
        self.txtIdLocalidad.setGeometry(QtCore.QRect(780, 160, 41, 23))
        self.txtIdLocalidad.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtIdLocalidad.setObjectName("txtIdLocalidad")
        self.txtLocalidad = QtGui.QLineEdit(Form)
        self.txtLocalidad.setGeometry(QtCore.QRect(820, 160, 231, 23))
        self.txtLocalidad.setObjectName("txtLocalidad")
        self.txtObservacion = QtGui.QTextEdit(Form)
        self.txtObservacion.setGeometry(QtCore.QRect(330, 220, 751, 51))
        self.txtObservacion.setObjectName("txtObservacion")
        self.lblObservacion = QtGui.QLabel(Form)
        self.lblObservacion.setGeometry(QtCore.QRect(330, 200, 231, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblObservacion.setPalette(palette)
        self.lblObservacion.setObjectName("lblObservacion")
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 290, 1071, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btnUbicacionBuscar = QtGui.QPushButton(Form)
        self.btnUbicacionBuscar.setGeometry(QtCore.QRect(280, 220, 31, 23))
        self.btnUbicacionBuscar.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../img/contactos/building-5-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUbicacionBuscar.setIcon(icon9)
        self.btnUbicacionBuscar.setObjectName("btnUbicacionBuscar")
        self.txtIdUbicacion = QtGui.QLineEdit(Form)
        self.txtIdUbicacion.setGeometry(QtCore.QRect(10, 220, 41, 23))
        self.txtIdUbicacion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txtIdUbicacion.setObjectName("txtIdUbicacion")
        self.lblUbicacion = QtGui.QLabel(Form)
        self.lblUbicacion.setGeometry(QtCore.QRect(10, 200, 181, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 32, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblUbicacion.setPalette(palette)
        self.lblUbicacion.setObjectName("lblUbicacion")
        self.txtUbicacion = QtGui.QLineEdit(Form)
        self.txtUbicacion.setGeometry(QtCore.QRect(50, 220, 231, 23))
        self.txtUbicacion.setObjectName("txtUbicacion")
        self.btnExportar = QtGui.QPushButton(Form)
        self.btnExportar.setGeometry(QtCore.QRect(510, 10, 91, 41))
        self.btnExportar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../img/OfficeExcel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportar.setIcon(icon10)
        self.btnExportar.setObjectName("btnExportar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNuevo.setText(QtGui.QApplication.translate("Form", "&Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificar.setText(QtGui.QApplication.translate("Form", "&Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminar.setText(QtGui.QApplication.translate("Form", "&Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeshacer.setText(QtGui.QApplication.translate("Form", "&Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setText(QtGui.QApplication.translate("Form", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLimpiar.setText(QtGui.QApplication.translate("Form", "&Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.lblId.setText(QtGui.QApplication.translate("Form", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCedula.setText(QtGui.QApplication.translate("Form", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCodigo.setText(QtGui.QApplication.translate("Form", "Codigo", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNombre.setText(QtGui.QApplication.translate("Form", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.lblApellido.setText(QtGui.QApplication.translate("Form", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsuarioRed.setText(QtGui.QApplication.translate("Form", "Usuario de Red", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTipoContacto.setText(QtGui.QApplication.translate("Form", "Tipo de Contacto", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelefonoOficina.setText(QtGui.QApplication.translate("Form", "Telefono Oficina", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTelefonoMovil.setText(QtGui.QApplication.translate("Form", "Telefono Movil", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("Form", "Correo electronico", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDpto.setText(QtGui.QApplication.translate("Form", "Departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLocalidad.setText(QtGui.QApplication.translate("Form", "Localidad", None, QtGui.QApplication.UnicodeUTF8))
        self.lblObservacion.setText(QtGui.QApplication.translate("Form", "Observacion", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUbicacion.setText(QtGui.QApplication.translate("Form", "Ubicacion: Area o Piso", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setToolTip(QtGui.QApplication.translate("Form", "Exportar consulta a MS Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportar.setText(QtGui.QApplication.translate("Form", "&Exportar", None, QtGui.QApplication.UnicodeUTF8))

