# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ods.ui'
#
# Created: Thu Mar  7 14:02:08 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1099, 621)
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 400, 241, 23))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(670, 380, 111, 16))
        self.label_13.setObjectName("label_13")
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 111, 16))
        self.label_7.setObjectName("label_7")
        self.txtCreadoPor = QtGui.QLineEdit(Form)
        self.txtCreadoPor.setGeometry(QtCore.QRect(630, 230, 221, 23))
        self.txtCreadoPor.setObjectName("txtCreadoPor")
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(20, 510, 111, 16))
        self.label_12.setObjectName("label_12")
        self.plainTextEdit = QtGui.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 530, 901, 83))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(630, 210, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 210, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(800, 400, 113, 23))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(410, 380, 111, 16))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(470, 210, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(800, 380, 111, 16))
        self.label_15.setObjectName("label_15")
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(20, 380, 121, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(410, 400, 113, 23))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(540, 380, 101, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(860, 230, 221, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.cbxEstado = QtGui.QComboBox(Form)
        self.cbxEstado.setGeometry(QtCore.QRect(150, 230, 151, 23))
        self.cbxEstado.setEditable(False)
        self.cbxEstado.setObjectName("cbxEstado")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 210, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(280, 380, 111, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 310, 221, 23))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(670, 400, 113, 23))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(860, 210, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 450, 111, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 230, 113, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 470, 901, 23))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(280, 400, 113, 23))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(540, 400, 113, 23))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.btnCombo = QtGui.QPushButton(Form)
        self.btnCombo.setGeometry(QtCore.QRect(30, 110, 89, 27))
        self.btnCombo.setObjectName("btnCombo")
        self.dateTimeEdit = QtGui.QDateTimeEdit(Form)
        self.dateTimeEdit.setGeometry(QtCore.QRect(310, 230, 151, 23))
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(Form)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(470, 230, 151, 23))
        self.dateTimeEdit_2.setWrapping(False)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.cbxEstado)
        Form.setTabOrder(self.cbxEstado, self.dateTimeEdit)
        Form.setTabOrder(self.dateTimeEdit, self.dateTimeEdit_2)
        Form.setTabOrder(self.dateTimeEdit_2, self.txtCreadoPor)
        Form.setTabOrder(self.txtCreadoPor, self.lineEdit_5)
        Form.setTabOrder(self.lineEdit_5, self.lineEdit_7)
        Form.setTabOrder(self.lineEdit_7, self.lineEdit_9)
        Form.setTabOrder(self.lineEdit_9, self.lineEdit_10)
        Form.setTabOrder(self.lineEdit_10, self.lineEdit_11)
        Form.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        Form.setTabOrder(self.lineEdit_12, self.lineEdit_14)
        Form.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        Form.setTabOrder(self.lineEdit_15, self.lineEdit_8)
        Form.setTabOrder(self.lineEdit_8, self.plainTextEdit)
        Form.setTabOrder(self.plainTextEdit, self.btnCombo)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Prioridad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Usuario Afectado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Orden de Servicio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Creado Por", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Fecha Apertura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Fecha Cierre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Soportista", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Area de Incidente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Asignado a:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Organizacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Reportado Por", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Asunto", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCombo.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.dateTimeEdit_2.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))

