# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ods.ui'
#
# Created: Sun Mar 10 02:33:23 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 465)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 250, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 250, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 250, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 250, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(350, 190, 241, 23))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 350, 111, 16))
        self.label_12.setObjectName("label_12")
        self.plainTextEdit = QtGui.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 370, 1081, 83))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.label.setObjectName("label")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 110, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(310, 170, 121, 16))
        self.label_11.setObjectName("label_11")
        self.cbxEstado = QtGui.QComboBox(Form)
        self.cbxEstado.setGeometry(QtCore.QRect(140, 130, 171, 23))
        self.cbxEstado.setEditable(False)
        self.cbxEstado.setObjectName("cbxEstado")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(640, 170, 111, 16))
        self.label_9.setObjectName("label_9")
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(830, 110, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(10, 290, 111, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 130, 113, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 310, 1081, 23))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(680, 190, 151, 23))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.txtFechaApertura = QtGui.QDateTimeEdit(Form)
        self.txtFechaApertura.setGeometry(QtCore.QRect(320, 130, 171, 23))
        self.txtFechaApertura.setWrapping(False)
        self.txtFechaApertura.setCalendarPopup(True)
        self.txtFechaApertura.setObjectName("txtFechaApertura")
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(310, 190, 41, 23))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 190, 31, 23))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/megaphone-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 190, 31, 23))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/building-5-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(640, 190, 41, 23))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1060, 190, 31, 23))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/user-14-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(870, 170, 111, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(910, 190, 151, 23))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(870, 190, 41, 23))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 250, 31, 23))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/tag-4-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(10, 230, 111, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(50, 250, 151, 23))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 250, 41, 23))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(280, 250, 151, 23))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(240, 230, 111, 16))
        self.label_18.setObjectName("label_18")
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 250, 31, 23))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/user-12-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(240, 250, 41, 23))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.cbxEstado_2 = QtGui.QComboBox(Form)
        self.cbxEstado_2.setGeometry(QtCore.QRect(470, 250, 151, 23))
        self.cbxEstado_2.setEditable(False)
        self.cbxEstado_2.setObjectName("cbxEstado_2")
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(470, 230, 61, 16))
        self.label_8.setObjectName("label_8")
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1291, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 248, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 213, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 119, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 216, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 248, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 213, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 119, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 216, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 248, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 213, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 119, 146))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 89, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 178, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.btnSalir = QtGui.QPushButton(self.widget)
        self.btnSalir.setGeometry(QtCore.QRect(1000, 10, 91, 41))
        self.btnSalir.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/25px_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon5)
        self.btnSalir.setObjectName("btnSalir")
        self.btnDeshacer = QtGui.QPushButton(Form)
        self.btnDeshacer.setGeometry(QtCore.QRect(310, 10, 91, 41))
        self.btnDeshacer.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/40px_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeshacer.setIcon(icon6)
        self.btnDeshacer.setObjectName("btnDeshacer")
        self.btnModificar = QtGui.QPushButton(Form)
        self.btnModificar.setEnabled(False)
        self.btnModificar.setGeometry(QtCore.QRect(110, 10, 91, 41))
        self.btnModificar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/40px-Crystal_Clear_app_kedit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModificar.setIcon(icon7)
        self.btnModificar.setObjectName("btnModificar")
        self.btnLimpiar = QtGui.QPushButton(Form)
        self.btnLimpiar.setGeometry(QtCore.QRect(410, 10, 91, 41))
        self.btnLimpiar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLimpiar.setIcon(icon8)
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.btnNuevo = QtGui.QPushButton(Form)
        self.btnNuevo.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.btnNuevo.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/30px-Crystal_Clear_app_List_manager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNuevo.setIcon(icon9)
        self.btnNuevo.setObjectName("btnNuevo")
        self.btnEliminar = QtGui.QPushButton(Form)
        self.btnEliminar.setGeometry(QtCore.QRect(210, 10, 91, 41))
        self.btnEliminar.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/30px_1 (514).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon10)
        self.btnEliminar.setObjectName("btnEliminar")
        self.lblCreadoPor = QtGui.QLabel(Form)
        self.lblCreadoPor.setGeometry(QtCore.QRect(500, 110, 111, 16))
        self.lblCreadoPor.setObjectName("lblCreadoPor")
        self.txtIdCreadoPor = QtGui.QLineEdit(Form)
        self.txtIdCreadoPor.setGeometry(QtCore.QRect(500, 130, 41, 23))
        self.txtIdCreadoPor.setObjectName("txtIdCreadoPor")
        self.btnCreadoPor = QtGui.QPushButton(Form)
        self.btnCreadoPor.setGeometry(QtCore.QRect(760, 130, 31, 23))
        self.btnCreadoPor.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/user-6-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreadoPor.setIcon(icon11)
        self.btnCreadoPor.setObjectName("btnCreadoPor")
        self.txtCreadoPor = QtGui.QLineEdit(Form)
        self.txtCreadoPor.setGeometry(QtCore.QRect(540, 130, 221, 23))
        self.txtCreadoPor.setObjectName("txtCreadoPor")
        self.btnReportadoPor = QtGui.QPushButton(Form)
        self.btnReportadoPor.setGeometry(QtCore.QRect(1060, 130, 31, 23))
        self.btnReportadoPor.setText("")
        self.btnReportadoPor.setIcon(icon11)
        self.btnReportadoPor.setObjectName("btnReportadoPor")
        self.txtIdReportadoPor = QtGui.QLineEdit(Form)
        self.txtIdReportadoPor.setGeometry(QtCore.QRect(800, 130, 41, 23))
        self.txtIdReportadoPor.setObjectName("txtIdReportadoPor")
        self.txtReportadoPor = QtGui.QLineEdit(Form)
        self.txtReportadoPor.setGeometry(QtCore.QRect(840, 130, 221, 23))
        self.txtReportadoPor.setObjectName("txtReportadoPor")
        self.btnAfectado = QtGui.QPushButton(Form)
        self.btnAfectado.setGeometry(QtCore.QRect(270, 190, 31, 23))
        self.btnAfectado.setText("")
        self.btnAfectado.setIcon(icon11)
        self.btnAfectado.setObjectName("btnAfectado")
        self.txtAfectado = QtGui.QLineEdit(Form)
        self.txtAfectado.setGeometry(QtCore.QRect(50, 190, 221, 23))
        self.txtAfectado.setObjectName("txtAfectado")
        self.txtIdAfectado = QtGui.QLineEdit(Form)
        self.txtIdAfectado.setGeometry(QtCore.QRect(10, 190, 41, 23))
        self.txtIdAfectado.setObjectName("txtIdAfectado")
        self.txtFechaModificacion = QtGui.QDateTimeEdit(Form)
        self.txtFechaModificacion.setGeometry(QtCore.QRect(630, 250, 151, 23))
        self.txtFechaModificacion.setWrapping(False)
        self.txtFechaModificacion.setCalendarPopup(True)
        self.txtFechaModificacion.setObjectName("txtFechaModificacion")
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(630, 230, 141, 16))
        self.label_4.setObjectName("label_4")
        self.txtFechaCierre = QtGui.QDateTimeEdit(Form)
        self.txtFechaCierre.setEnabled(True)
        self.txtFechaCierre.setGeometry(QtCore.QRect(790, 250, 151, 23))
        self.txtFechaCierre.setWrapping(False)
        self.txtFechaCierre.setCalendarPopup(True)
        self.txtFechaCierre.setObjectName("txtFechaCierre")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(790, 230, 141, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btnNuevo, self.btnModificar)
        Form.setTabOrder(self.btnModificar, self.btnEliminar)
        Form.setTabOrder(self.btnEliminar, self.btnDeshacer)
        Form.setTabOrder(self.btnDeshacer, self.btnLimpiar)
        Form.setTabOrder(self.btnLimpiar, self.btnSalir)
        Form.setTabOrder(self.btnSalir, self.lineEdit)
        Form.setTabOrder(self.lineEdit, self.cbxEstado)
        Form.setTabOrder(self.cbxEstado, self.txtFechaApertura)
        Form.setTabOrder(self.txtFechaApertura, self.txtIdCreadoPor)
        Form.setTabOrder(self.txtIdCreadoPor, self.txtCreadoPor)
        Form.setTabOrder(self.txtCreadoPor, self.btnCreadoPor)
        Form.setTabOrder(self.btnCreadoPor, self.lineEdit_13)
        Form.setTabOrder(self.lineEdit_13, self.lineEdit_9)
        Form.setTabOrder(self.lineEdit_9, self.pushButton)
        Form.setTabOrder(self.pushButton, self.lineEdit_16)
        Form.setTabOrder(self.lineEdit_16, self.lineEdit_10)
        Form.setTabOrder(self.lineEdit_10, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.lineEdit_18)
        Form.setTabOrder(self.lineEdit_18, self.lineEdit_17)
        Form.setTabOrder(self.lineEdit_17, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.lineEdit_20)
        Form.setTabOrder(self.lineEdit_20, self.lineEdit_19)
        Form.setTabOrder(self.lineEdit_19, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.lineEdit_22)
        Form.setTabOrder(self.lineEdit_22, self.lineEdit_21)
        Form.setTabOrder(self.lineEdit_21, self.pushButton_5)
        Form.setTabOrder(self.pushButton_5, self.cbxEstado_2)
        Form.setTabOrder(self.cbxEstado_2, self.lineEdit_8)
        Form.setTabOrder(self.lineEdit_8, self.plainTextEdit)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Reporte de Incidentes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Usuario Afectado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Orden de Servicio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Fecha Apertura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Area de Incidente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Organizacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Reportado Por", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Asunto", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFechaApertura.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Grupo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Asignado a:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Soportista", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Prioridad", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setToolTip(QtGui.QApplication.translate("Form", "Salir del Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSalir.setText(QtGui.QApplication.translate("Form", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeshacer.setText(QtGui.QApplication.translate("Form", "&Deshacer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModificar.setText(QtGui.QApplication.translate("Form", "&Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLimpiar.setText(QtGui.QApplication.translate("Form", "&Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNuevo.setText(QtGui.QApplication.translate("Form", "&Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEliminar.setText(QtGui.QApplication.translate("Form", "&Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCreadoPor.setText(QtGui.QApplication.translate("Form", "Creado Por", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFechaModificacion.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Fecha Modificacion", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFechaCierre.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Fecha Cierre", None, QtGui.QApplication.UnicodeUTF8))

